### PR TITLE
Dependencies version of python packages changed, added code to sparse…

### PR DESCRIPTION
**Pull request by jamesh14**
…=True to pd.get_dummies() for oneHotEcoding to reduce memory consumption

### CODE REVIEW

**Comment by cass12345** [comment]
can u also check the packages' versions in the dockerfile? I think I'm using the newest version for all

**Comment by jamesh14** [comment]
> can u also check the packages' versions in the dockerfile? I think I'm using the newest version for all

I tried to use the old dependencies, but I was getting some error when I run the analysis file.

**Comment by cass12345** [comment]
i don't quite get the point tho, but we are all aiming to use the updated version for the packages in dockerfile right?

**Comment by jamesh14** [comment]
> i don't quite get the point tho, but we are all aiming to use the updated version for the packages in dockerfile right?

I think its because some of the newer packages version aren't compatible with the other ones? That's why I used some of the older versions to mke sure that they are compatible.

I don't think the newer package versions would affect the code.

**Comment by cass12345** [comment]
the newer, the better. lol some older packages may not contain of the functions that we use in the code or maybe they have a different name of the functions

**Pull request merged**
